version: "3"
services:
  # container_name: db
  # postgres:
  #   image: postgres:11
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=postgres
  
  web:
    container_name: backend
    build: 
      context: backend
    ports:
      - 80:80
    volumes:
      - ./backend:/app
    # depends_on:
    #   - postgres
